# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-08 06:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webframe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preference',
            options={'permissions': (('browse_config', 'Can browse system configuration'), ('browse_preference', 'Can browse other preferences'))},
        ),
        migrations.RemoveField(
            model_name='preference',
            name='user',
        ),
        migrations.AddField(
            model_name='preference',
            name='enabled',
            field=models.BooleanField(default=True, help_text='ValueObject.enabled.helptext', verbose_name='ValueObject.enabled'),
        ),
        migrations.AddField(
            model_name='preference',
            name='lmb',
            field=models.ForeignKey(blank=True, help_text='ValueObject.lmb.helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preference_lmd', to=settings.AUTH_USER_MODEL, verbose_name='ValueObject.lmb'),
        ),
        migrations.AddField(
            model_name='preference',
            name='lmd',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 8, 6, 13, 28, 527051, tzinfo=utc), help_text='ValueObject.lmd.helptext', verbose_name='ValueObject.lmd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Preference.owner.helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preference_owner', to=settings.AUTH_USER_MODEL, verbose_name='Preference.owner'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Preference.id.helptext', primary_key=True, serialize=False, verbose_name='Preference.id'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='name',
            field=models.CharField(help_text='Preference.name.helptext', max_length=100, verbose_name='Preference.name'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Preference.parent.helptext', null=True, on_delete=django.db.models.deletion.CASCADE, to='webframe.Preference', verbose_name='Preference.parent'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='sequence',
            field=models.FloatField(default=0.5, help_text='Preference.sequence.helptext', verbose_name='Preference.sequence'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='value',
            field=models.CharField(help_text='Preference.value.helptext', max_length=1024, verbose_name='Preference.value'),
        ),
    ]
