# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0004_privilege'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preference',
            options={'permissions': (('add_config', 'Can add configuration'), ('change_config', 'Can change configuration'), ('delete_config', 'Can delete configuration'), ('browse_config', 'Can browse system configuration'), ('browse_preference', 'Can browse other preferences'))},
        ),
    ]
