# Generated by Django 3.1.1 on 2020-10-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0013_PrefEncryption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numbering',
            options={'permissions': [('exec_numbering', 'Can execute the number')], 'verbose_name': 'webframe.models.Numbering', 'verbose_name_plural': 'webframe.models.Numberings'},
        ),
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='preference',
            constraint=models.UniqueConstraint(fields=('name', 'owner', 'parent'), name='unique_name_and_owner'),
        ),
        migrations.AddConstraint(
            model_name='preference',
            constraint=models.UniqueConstraint(condition=models.Q(owner=None), fields=('name', 'parent'), name='unique_name'),
        ),
    ]
