# Generated by Django 3.1.2 on 2020-10-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0014_unique_pref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbering',
            name='pattern',
            field=models.CharField(default='{next}', help_text='webframe.models.Numbering.pattern.helptxt', max_length=100, verbose_name='webframe.models.Numbering.pattern'),
        ),
    ]
