# Generated by Django 3.1.3 on 2021-01-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0017_profile'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='preference',
            name='unique_name',
        ),
        migrations.AddField(
            model_name='preference',
            name='lang',
            field=models.CharField(blank=True, help_text='webframe.models.Preference.lang.helptext', max_length=20, null=True, verbose_name='webframe.models.Preference.lang'),
        ),
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together={('name', 'lang')},
        ),
    ]
