# Generated by Django 3.1.3 on 2021-07-09 11:25

from django.db import migrations, models
import webframe.models


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0018_preference_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='filecontent',
            field=models.FileField(blank=True, help_text='webframe.models.Preference.filecontent.helptext', max_length=1024, null=True, upload_to=webframe.models.AbstractPreference.get_filecontent_location, verbose_name='webframe.models.Preference.filecontent'),
        ),
    ]
