# Generated by Django 3.2.6 on 2021-08-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0020_merge_0019_preference_filecontent_0019_unique_PrefKey'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbering',
            name='desc',
            field=models.CharField(blank=True, help_text='webframe.models.Numbering.desc.helptext', max_length=1024, null=True, verbose_name='webframe.models.Numbering.desc'),
        ),
        migrations.AlterField(
            model_name='numbering',
            name='name',
            field=models.CharField(help_text='webframe.models.Numbering.name.helptxt', max_length=100, unique=True, verbose_name='webframe.models.Numbering.name'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='sequence',
            field=models.FloatField(default=9223372036854775807, help_text='webframe.models.Preference.sequence.helptext', verbose_name='webframe.models.Preference.sequence'),
        ),
    ]
