# Generated by Django 3.2.6 on 2022-08-12 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webframe.CurrentUserMiddleware
import webframe.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webframe', '0023_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthnPubkey',
            fields=[
                ('lmd', models.DateTimeField(auto_now=True, help_text='ValueObject.lmd.helptext', verbose_name='ValueObject.lmd')),
                ('cd', models.DateTimeField(auto_now_add=True, help_text='ValueObject.cd.helptext', verbose_name='ValueObject.cd')),
                ('id', models.CharField(help_text='WebAuthnPubkey.id.helptext', max_length=1024, primary_key=True, serialize=False, verbose_name='WebAuthnPubkey.id')),
                ('pubkey', models.CharField(help_text='WebAuthnPubkey.pubkey.helptext', max_length=1024, unique=True, verbose_name='WebAuthnPubkey.pubkey')),
                ('tipe', models.CharField(help_text='WebAuthnPubkey.tipe.helptext', max_length=1024, verbose_name='WebAuthnPubkey.tipe')),
                ('signCount', models.IntegerField(help_text='WebAuthnPubkey.signCount.helptext', verbose_name='WebAuthnPubkey.signCount')),
                ('cb', models.ForeignKey(blank=True, default=webframe.CurrentUserMiddleware.get_current_user, help_text='ValueObject.cb.helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webauthnpubkey_cb', to=settings.AUTH_USER_MODEL, verbose_name='ValueObject.cb')),
                ('lmb', models.ForeignKey(blank=True, default=webframe.CurrentUserMiddleware.get_current_user, help_text='ValueObject.lmb.helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webauthnpubkey_lmb', to=settings.AUTH_USER_MODEL, verbose_name='ValueObject.lmb')),
                ('owner', models.ForeignKey(help_text='WebAuthnPubkey.owner.helptext', on_delete=django.db.models.deletion.CASCADE, related_name='WebAuthnPubkey_owner', to=settings.AUTH_USER_MODEL, verbose_name='WebAuthnPubkey.owner')),
            ],
            options={
                'verbose_name': 'WebAuthnPubkey',
                'verbose_name_plural': 'WebAuthnPubkeies',
            },
            bases=(models.Model, webframe.models.Dictable),
        ),
    ]
