# Generated by Django 3.1.7 on 2021-11-11 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
import webframe.CurrentUserMiddleware
import webframe.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webframe', '0023_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ValueObject.id.helptext', primary_key=True, serialize=False, verbose_name='ValueObject.id')),
                ('lmd', models.DateTimeField(auto_now=True, help_text='ValueObject.lmd.helptext', verbose_name='ValueObject.lmd')),
                ('cd', models.DateTimeField(auto_now_add=True, help_text='ValueObject.cd.helptext', verbose_name='ValueObject.cd')),
                ('effDate', models.DateTimeField(default=django.utils.timezone.now, help_text='AliveObject.effDate.helptext', verbose_name='AliveObject.effDate')),
                ('expDate', models.DateTimeField(blank=True, help_text='AliveObject.expDate.helptext', null=True, verbose_name='AliveObject.expDate')),
                ('enabled', models.BooleanField(default=True, help_text='AliveObject.enabled.helptext', verbose_name='AliveObject.enabled')),
                ('key', models.CharField(default='WillBeGeneratedAutomatically', help_text='ResetPassword.key.helptext', max_length=100, verbose_name='ResetPassword.key')),
                ('request_by', models.CharField(help_text='ResetPassword.request_by.helptext', max_length=50, verbose_name='ResetPasssword.request_by')),
                ('complete_by', models.CharField(blank=True, help_text='ResetPassword.complete_by.helptext', max_length=50, null=True, verbose_name='ResetPasssword.complete_by')),
                ('complete_date', models.DateTimeField(blank=True, help_text='ResetPassword.complete_date.helptext', null=True, verbose_name='ResetPassword.complete_date')),
                ('cb', models.ForeignKey(blank=True, default=webframe.CurrentUserMiddleware.get_current_user, help_text='ValueObject.cb.helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resetpassword_cb', to=settings.AUTH_USER_MODEL, verbose_name='ValueObject.cb')),
                ('lmb', models.ForeignKey(blank=True, default=webframe.CurrentUserMiddleware.get_current_user, help_text='ValueObject.lmb.helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resetpassword_lmb', to=settings.AUTH_USER_MODEL, verbose_name='ValueObject.lmb')),
                ('user', models.ForeignKey(help_text='ResetPassword.user.helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resetPassword_user', to=settings.AUTH_USER_MODEL, verbose_name='ResetPassword.user')),
            ],
            options={
                'verbose_name': 'ResetPassword',
                'verbose_name_plural': 'ResetPasswords',
                'unique_together': {('key', 'user')},
            },
            bases=(models.Model, webframe.models.Dictable),
        ),
    ]
