# Generated by Django 2.1 on 2018-10-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0005_PreferencesPermissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='value',
            field=models.TextField(blank=True, help_text='webframe.models.Preference.value.helptext', max_length=4096, null=True, verbose_name='webframe.models.Preference.value'),
        ),
    ]
