# Generated by Django 2.2.2 on 2019-06-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0006_PrefValue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privilege',
            name='contenttype',
        ),
        migrations.AddField(
            model_name='preference',
            name='reserved',
            field=models.BooleanField(default=False, help_text='webframe.models.Preference.reserved.helptext', verbose_name='webframe.models.Preference.reserved'),
        ),
        migrations.DeleteModel(
            name='GrantedPrivilege',
        ),
        migrations.DeleteModel(
            name='Privilege',
        ),
    ]
