# Generated by Django 2.0.3 on 2019-10-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0007_preference_reserved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preference',
            options={'permissions': (('add_config', 'Can add configuration'), ('change_config', 'Can change configuration'), ('delete_config', 'Can delete configuration'), ('browse_config', 'Can browse system configuration'), ('browse_preference', 'Can browse other preferences'), ('change_preference_type', 'Can change the preference type'))},
        ),
        migrations.AddField(
            model_name='preference',
            name='tipe',
            field=models.IntegerField(choices=[(0, 'webframe.models.Preference.TYPE.NONE'), (1, 'webframe.models.Preference.TYPE.INT'), (2, 'webframe.models.Preference.TYPE.DECIMAL'), (3, 'webframe.models.Preference.TYPE.BOOLEAN'), (4, 'webframe.models.Preference.TYPE.TEXT'), (5, 'webframe.models.Preference.TYPE.RICHTEXT'), (6, 'webframe.models.Preference.TYPE.URL'), (7, 'webframe.models.Preference.TYPE.EMAIL'), (8, 'webframe.models.Preference.TYPE.DATE'), (9, 'webframe.models.Preference.TYPE.TIME'), (10, 'webframe.models.Preference.TYPE.DATETIME')], default=4, help_text='webframe.models.Preference.tipe.helptext', verbose_name='webframe.models.Preference.tipe'),
        ),
    ]
