# Generated by Django 2.0.3 on 2020-01-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0008_PreferenceType'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='tipe',
            field=models.IntegerField(choices=[(0, 'webframe.models.Preference.TYPE.NONE'), (1, 'webframe.models.Preference.TYPE.INT'), (2, 'webframe.models.Preference.TYPE.DECIMAL'), (3, 'webframe.models.Preference.TYPE.BOOLEAN'), (4, 'webframe.models.Preference.TYPE.TEXT'), (5, 'webframe.models.Preference.TYPE.RICHTEXT'), (6, 'webframe.models.Preference.TYPE.URL'), (7, 'webframe.models.Preference.TYPE.EMAIL'), (8, 'webframe.models.Preference.TYPE.DATE'), (9, 'webframe.models.Preference.TYPE.TIME'), (10, 'webframe.models.Preference.TYPE.DATETIME'), (11, 'webframe.models.Preference.TYPE.UUIDS'), (12, 'webframe.models.Preference.TYPE.LIST')], default=4, help_text='webframe.models.Preference.tipe.helptext', verbose_name='webframe.models.Preference.tipe'),
        ),
    ]
