# Generated by Django 3.0.4 on 2020-07-30 08:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webframe', '0010_preference_types'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together={('name', 'owner')},
        ),
    ]
