# Generated by Django 3.1.1 on 2020-10-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0012_numbering'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='value',
            new_name='_value',
        ),
        migrations.AddField(
            model_name='preference',
            name='encrypted',
            field=models.BooleanField(default=False, help_text='webframe.models.Preference.encrypted.helptxt', verbose_name='webframe.models.Preference.encrypted'),
        ),
    ]
