# Generated by Django 3.1.4 on 2020-12-27 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
import webframe.CurrentUserMiddleware
import webframe.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webframe', '0016_helptext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='_tipe',
            field=models.IntegerField(choices=[(0, 'webframe.models.Preference.TYPE.NONE'), (1, 'webframe.models.Preference.TYPE.INT'), (2, 'webframe.models.Preference.TYPE.DECIMAL'), (3, 'webframe.models.Preference.TYPE.BOOLEAN'), (4, 'webframe.models.Preference.TYPE.TEXT'), (5, 'webframe.models.Preference.TYPE.RICHTEXT'), (6, 'webframe.models.Preference.TYPE.URL'), (7, 'webframe.models.Preference.TYPE.EMAIL'), (8, 'webframe.models.Preference.TYPE.DATE'), (9, 'webframe.models.Preference.TYPE.TIME'), (10, 'webframe.models.Preference.TYPE.DATETIME'), (11, 'webframe.models.Preference.TYPE.UUIDS'), (12, 'webframe.models.Preference.TYPE.LIST'), (13, 'webframe.models.Preference.TYPE.JSON'), (14, 'webframe.models.Preference.TYPE.FILEPATH')], default=4, help_text='webframe.models.Preference.tipe.helptext', verbose_name='webframe.models.Preference.tipe'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='webframe.models.ValueObject.id.helptext', primary_key=True, serialize=False, verbose_name='webframe.models.ValueObject.id')),
                ('lmd', models.DateTimeField(auto_now=True, help_text='webframe.models.ValueObject.lmd.helptext', verbose_name='webframe.models.ValueObject.lmd')),
                ('cd', models.DateTimeField(auto_now_add=True, help_text='webframe.models.ValueObject.cd.helptext', verbose_name='webframe.models.ValueObject.cd')),
                ('effDate', models.DateTimeField(default=django.utils.timezone.now, help_text='webframe.models.AliveObject.effDate.helptext', verbose_name='webframe.models.AliveObject.effDate')),
                ('expDate', models.DateTimeField(blank=True, help_text='webframe.models.AliveObject.expDate.helptext', null=True, verbose_name='webframe.models.AliveObject.expDate')),
                ('enabled', models.BooleanField(default=True, help_text='webframe.models.AliveObject.enabled.helptext', verbose_name='webframe.models.AliveObject.enabled')),
                ('cb', models.ForeignKey(blank=True, default=webframe.CurrentUserMiddleware.get_current_user, help_text='webframe.models.ValueObject.cb.helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_cb', to=settings.AUTH_USER_MODEL, verbose_name='webframe.models.ValueObject.cb')),
                ('lmb', models.ForeignKey(blank=True, default=webframe.CurrentUserMiddleware.get_current_user, help_text='webframe.models.ValueObject.lmb.helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_lmb', to=settings.AUTH_USER_MODEL, verbose_name='webframe.models.ValueObject.lmb')),
                ('user', models.OneToOneField(help_text='webframe.models.Profile.helptext', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='webframe.models.Profile')),
            ],
            options={
                'verbose_name': 'webframe.models.Profile',
                'verbose_name_plural': 'webframe.models.Profiles',
            },
            bases=(models.Model, webframe.models.Dictable),
        ),
    ]
