# Generated by Django 3.2.6 on 2021-08-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0018_preference_lang'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='preference',
            name='unique_name_and_owner',
        ),
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together={('parent', 'name', 'lang')},
        ),
        migrations.AddConstraint(
            model_name='preference',
            constraint=models.UniqueConstraint(fields=('name', 'owner', 'parent'), name='unique_name_owner_n_parent'),
        ),
    ]
