# Generated by Django 3.2.6 on 2021-08-15 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0019_preference_filecontent'),
        ('webframe', '0019_unique_PrefKey'),
    ]

    operations = [
    ]
