# Generated by Django 3.2.6 on 2022-08-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0026_webauthnpubkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='webauthnpubkey',
            name='lastSignin',
            field=models.DateTimeField(blank=True, help_text='WebAuthnPubkey.lastSignin', null=True, verbose_name='WebAuthnPubkey.lastSignin'),
        ),
    ]
