# Generated by Django 3.2.15 on 2022-09-07 09:36

from django.db import migrations

def merge(apps, schema_editor):
   if schema_editor.connection.alias != 'default': return
   MenuItem=apps.get_model('webframe', 'MenuItem')
   for mi in MenuItem.objects.all():
      if mi.mousein: mi.props['mousein']=mi.mousein
      if mi.mouseout: mi.props['mouseout']=mi.mouseout
      if mi.onclick: mi.props['onclick']=mi.onclick
      mi.save()

class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0028_webauthnpubkey_ipaddr'),
    ]

    operations = [
      migrations.RunPython(merge),
    ]
