# Generated by Django 3.2.15 on 2022-09-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webframe', '0029_menuitem_props'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='mousein',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='mouseout',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='onclick',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='props',
            field=models.JSONField(blank=True, default={'class': None, 'onclick': 'window.location.href=this.data.props.href?this.data.props.href:"#";', 'style': None, 'target': None, 'title': None}, help_text='MenuItem.props.help', null=True, verbose_name='MenuItem.props'),
        ),
    ]
